<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <RootNamespace>SaveDataExporter</RootNamespace>
        <AssemblyName>SaveDataExporter</AssemblyName>
        <PackageId>SaveDataExporter</PackageId>
        <Version>1.0.0</Version>
        <Description>DSP MOD - Save Data Exporter</Description>
        <BepInExPluginGuid>com.menglei.dsp.savedataexporter</BepInExPluginGuid>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.17"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.0.0"/>
        <PackageReference Include="UnityEngine.Modules" Version="2022.3.53" IncludeAssets="compile"/>
        <PackageReference Include="DysonSphereProgram.Modding.CommonAPI" Version="*-*"/>
        <PackageReference Include="DysonSphereProgram.GameLibs" Version="*-*"/>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/>
        <Reference Include="System.IO.Compression"/>
    </ItemGroup>
</Project>
