namespace UXAEnhance;

internal enum AutoConfigApplyTarget {
    DispenserChargePower,
    DispenserCourierCount,
    BattleBaseChargePower,
    PlsChargePower,
    PlsMaxTripDrone,
    PlsDroneMinDeliver,
    PlsMinPilerValue,
    PlsDroneCount,
    IlsChargePower,
    IlsMaxTripDrone,
    IlsMaxTripShip,
    IlsWarperDistance,
    IlsDroneMinDeliver,
    IlsShipMinDeliver,
    IlsMinPilerValue,
    IlsIncludeOrbitCollector,
    IlsWarperNecessary,
    IlsDroneCount,
    IlsShipCount,
    VeinCollectorHarvestSpeed,
    VeinCollectorMinPilerValue,
}
